
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gumansingh
 */
public class business extends javax.swing.JFrame {

    /**
     * Creates new form business
     */
    DefaultTableModel Model;
    public business() {
        initComponents();
        setSize (1520, 750);
        initComponents();
        Model = (DefaultTableModel) tblEntry.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        aname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nage = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        agender = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        aemail = new javax.swing.JTextField();
        aphone = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        aage = new javax.swing.JTextField();
        aseat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aclasss = new javax.swing.JTextField();
        adeparture = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        aarrival = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntry = new javax.swing.JTable();
        exit = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                panel1PropertyChange(evt);
            }
        });
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel1.add(aname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, 30));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Name");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        nage.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        nage.setForeground(new java.awt.Color(255, 255, 0));
        nage.setText("Age");
        panel1.add(nage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        gender.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 0));
        gender.setText("Gender");
        panel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        panel1.add(agender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 160, 30));

        email.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 0));
        email.setText("Email");
        panel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        panel1.add(aemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 160, 30));
        panel1.add(aphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 160, 30));

        phone.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 0));
        phone.setText("Phone No");
        panel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));
        panel1.add(aage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 160, 30));
        panel1.add(aseat, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 160, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setText("First Class Passengers");
        jLabel3.setToolTipText("");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setText("Karachi Airline Service");
        jLabel4.setToolTipText("");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 580, 50));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Seat No");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Class");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));
        panel1.add(aclasss, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 160, 30));
        panel1.add(adeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 160, 30));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Departure");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Arrival");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));
        panel1.add(aarrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 160, 30));

        clear.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 51, 51));
        clear.setText("Clear");
        clear.setActionCommand("");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        panel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 70, 30));

        delete.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 51, 51));
        delete.setText("Delete");
        delete.setActionCommand("");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        panel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 80, 30));

        add.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 51, 51));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        panel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 70, 30));

        tblEntry.setBackground(new java.awt.Color(204, 204, 0));
        tblEntry.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblEntry.setForeground(new java.awt.Color(102, 51, 255));
        tblEntry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Guman Singh", "19", "Male", "guman390@gmail.com", "03327305601", "1812297", "First Class", "Karachi", "Hyderabad"},
                {"Jarnail Valasai", "19", "Male", "jvalasai@gmail.com", "03313656352", "1812300", "First Class", "Kaloi", "Karachi"},
                {"Manish Lohano", "21", "Male", "manishlohano321@gmail.com", "03312064979", "1812306", "First Class", "Mirpur Khas", "Hyderabad"},
                {"Kashif Tariq", "17", "Male", "evenbetter6@gmail.com", "03103488563", "1812309", "First Class", "Lahore", "Karachi"},
                {"Ambreen Malik", "18", "Female", "Not-Availabe", "03314634564", "1812306", "First Class", "Karachi", "Lahore"},
                {"Rayyan Zaidi", "20", "Male", "zaidir97@gmail.com", "03412156509", "1812323", "First Class", "Islamabad", "Karachi"}
            },
            new String [] {
                "Name", "Age", "Gender", "Email", "Phone No", "Seat No", "Class", "Departure", "Arrival"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEntry.getTableHeader().setReorderingAllowed(false);
        tblEntry.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tblEntryVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblEntry);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 1380, 380));

        exit.setBackground(new java.awt.Color(255, 102, 255));
        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(51, 0, 204));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        panel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 80, 40));

        Back.setBackground(new java.awt.Color(255, 102, 255));
        Back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(51, 0, 204));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        panel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 40));

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 1400, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        Model.removeRow(0);
    }//GEN-LAST:event_clearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if (tblEntry.getSelectedRow()== -1){
            JOptionPane.showMessageDialog(business.this,"Select any row first!");
            return;
        }
        Model.removeRow(tblEntry.getSelectedRow());
    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if (ValidateFields()){
            Model.insertRow(tblEntry.getRowCount(),new Object[]{
                aname.getText(),
                aage.getText(),
                agender.getText(),
                aemail.getText(),
                phone.getText(),
                aseat.getText(),
                aclasss.getText(),
                adeparture.getText(),
                aarrival.getText(),
            });
            resetField();
        }
    }//GEN-LAST:event_addActionPerformed
    private void panel1MouseClicked(java.awt.event.MouseEvent evt) {                                    
        tblEntry.clearSelection();
    }  
    private void tblEntryVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tblEntryVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEntryVetoableChange

    private void panel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_panel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_panel1PropertyChange
    private JFrame frame;
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        frame = new JFrame ("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Do you really want to Exit","Output Console",
            JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_NO_OPTION)){
        System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new ticketing().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new business().setVisible(true);
            }
        });
    }
        private boolean ValidateFields(){
            if (aname.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(business.this,"Enter your Name!");
                aname.grabFocus();
                return false;
            }
            if (aage.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(business.this,"Enter your Age!");
                aage.grabFocus();
                return false;
        }
            if (agender.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(business.this,"Enter your Gender!");
                agender.grabFocus();
                return false;
        }
            if (aemail.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(business.this,"Enter your Email!");
                aemail.grabFocus();
                return false;
        }
            if (aphone.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(business.this,"Enter your Phone Number!");
                aphone.grabFocus();
                return false;
        }
            if (aseat.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(business.this,"Enter your Seat Number!");
                aseat.grabFocus();
                return false;
        }
            if (aclasss.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(business.this,"Enter your Class!");
                aclasss.grabFocus();
                return false;
        }
            if (adeparture.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(business.this,"Enter Departure City!");
                adeparture.grabFocus();
                return false;
        }
            if (aarrival.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(business.this,"Enter Arrival City!");
                aarrival.grabFocus();
                return false;
        }
            return true;
        }
   private void resetField(){
       aname.setText("");
       aage.setText("");
       agender.setText("");
       aemail.setText("");
       phone.setText("");
       aseat.setText("");
       aclasss.setText("");
       adeparture.setText("");
       aarrival.setText("");
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField aage;
    private javax.swing.JTextField aarrival;
    private javax.swing.JTextField aclasss;
    private javax.swing.JButton add;
    private javax.swing.JTextField adeparture;
    private javax.swing.JTextField aemail;
    private javax.swing.JTextField agender;
    public javax.swing.JTextField aname;
    private javax.swing.JTextField aphone;
    private javax.swing.JTextField aseat;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel email;
    private javax.swing.JButton exit;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nage;
    private java.awt.Panel panel1;
    private javax.swing.JLabel phone;
    private javax.swing.JTable tblEntry;
    // End of variables declaration//GEN-END:variables
}
