
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gumansingh
 */
public class departure extends javax.swing.JFrame {

    /**
     * Creates new form departure
     */
    public departure() {
        initComponents();
        setSize (1520, 750);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(255, 255, 0));
        panel1.setLayout(null);

        table.setAutoCreateRowSorter(true);
        table.setBackground(new java.awt.Color(255, 255, 204));
        table.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        table.setForeground(new java.awt.Color(51, 51, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PK-324", "<html><font color=\"GREEN\">Terminal C</color></html>", "Islamabad", "<html><font color=\"RED\">40</color></html>", "6:30 am", "<html><font color=\"GREEN\">ON TIME</color></html>"},
                {"NY-481", "<html><font color=\"GREEN\">Terminal A</color></html>", "New York", "<html><font color=\"RED\">32</color></html>", "7:00 am", "<html><font color=\"RED\">DELAYED</color></html>"},
                {"KC-321", "<html><font color=\"GREEN\">Terminal B</color></html>", "Kolkata", "<html><font color=\"RED\">12</color></html>", "7:15 am", "<html><font color=\"green\">CHECK-IN</color></html>"},
                {"IT-392", "<html><font color=\"GREEN\">Terminal D</color></html>", "Rome", "<html><font color=\"RED\">11</color></html>", "8:30 am", "<html><font color=\"red\">CANCELLED</color></html>"},
                {"AU-342", "<html><font color=\"GREEN\">Terminal Z</color></html>", "Sydeny", "<html><font color=\"RED\">19</color></html>", "9:00 am", "<html><font color=\"GREEN\">ON TIME</color></html>"},
                {"QT-635", "<html><font color=\"GREEN\">Terminal B</color></html>", "Delhi", "<html><font color=\"RED\">21</color></html>", "9:20 am", "<html><font color=\"GREEN\">ON TIME</color></html>"},
                {"KM-321", "<html><font color=\"GREEN\">Terminal A</color></html>", "Khatmandu", "<html><font color=\"RED\">23</color></html>", "9:50 am", "<html><font color=\"RED\">DELAYED</color></html>"},
                {"UK-512", "<html><font color=\"GREEN\">Terminal C</color></html>", "London", "<html><font color=\"RED\">07</color></html>", "11:35 am", "<html><font color=\"GREEN\">ON TIME</color></html>"},
                {"AI-262", "<html><font color=\"GREEN\">Terminal D</color></html>", "Mumbai", "<html><font color=\"RED\">29</color></html>", "12:00 pm", "<html><font color=\"GREEN\">ON TIME</color></html>"},
                {"PK-291", "<html><font color=\"GREEN\">Terminal A</color></html>", "Lahore", "<html><font color=\"RED\">28</color></html>", "3:00 pm", "<html><font color=\"green\">CHECK-IN</color></html>"},
                {"TK-821", "<html><font color=\"GREEN\">Terminal B</color></html>", "Ankara", "<html><font color=\"RED\">27</color></html>", "6:00 pm", "<html><font color=\"red\">CANCELLED</color></html>"}
            },
            new String [] {
                "<html><body><h3><font color=\"BLUE\">FLIGHT</color></body></html>", "<html><body><h3><font color=\"green\">TERMINAL</color></body></html>", "<html><body><h3><font color=\"BLUE\">DESTINATION</color></body></html>", "<html><body><h3><font color=\"RED\">GATE</color></body></html>", "<html><body><h3><font color=\"BLUE\">TIME</color></body></html>", "<html><body><h3><font color=\"GREEN\">REMARKS</color></body></html>"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setSelectionForeground(new java.awt.Color(255, 51, 51));
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.getTableHeader().setResizingAllowed(false);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);

        panel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 170, 1400, 580);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("Karachi Airline Service");
        panel1.add(jLabel1);
        jLabel1.setBounds(380, 10, 690, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("DEPARTURE");
        panel1.add(jLabel2);
        jLabel2.setBounds(500, 100, 530, 50);

        exit.setBackground(new java.awt.Color(255, 102, 255));
        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(51, 0, 204));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        panel1.add(exit);
        exit.setBounds(110, 10, 80, 40);

        Back.setBackground(new java.awt.Color(255, 102, 255));
        Back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(51, 0, 204));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        panel1.add(Back);
        Back.setBounds(10, 10, 80, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guman Singh\\OneDrive\\Documents\\NetBeansProjects\\airline\\pics\\arrival.png")); // NOI18N
        jLabel3.setText("jLabel3");
        panel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1400, 720);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 1410, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JFrame frame;
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        frame = new JFrame ("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Do you really want to Exit","Output Console",
            JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_NO_OPTION)){
        System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new ticketing().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(departure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(departure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(departure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(departure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new departure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton delete;
    private javax.swing.JButton delete1;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
