
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gumansingh
 */
public class firstClass extends javax.swing.JFrame {

    /**
     * Creates new form firstClass
     */
    DefaultTableModel model;
    public firstClass() {
        initComponents();
        setSize (1520, 750);
        model = (DefaultTableModel) tblData.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        Age = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        email = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        Gender = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Class = new javax.swing.JTextField();
        seat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        departure = new javax.swing.JTextField();
        arrival = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        name4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 102));
        setForeground(new java.awt.Color(0, 153, 51));
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(51, 255, 51));
        panel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel1MouseClicked(evt);
            }
        });
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblData.setBackground(new java.awt.Color(204, 204, 0));
        tblData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblData.setForeground(new java.awt.Color(102, 51, 255));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Guman Singh", "19", "Male", "guman390@gmail.com", "03327305601", "1614", "First Class", "Karachi", "Hyderabad"}
            },
            new String [] {
                "Name", "Age", "Gender", "Email", "Phone No", "Seat No", "Class", "Departure", "Arrival"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.getTableHeader().setReorderingAllowed(false);
        tblData.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tblDataVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1360, 350));

        Age.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Age.setForeground(new java.awt.Color(255, 255, 0));
        Age.setText("Age");
        panel1.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
        panel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 160, 30));
        panel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, 30));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Name");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        clear.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 51, 51));
        clear.setText("Clear");
        clear.setActionCommand("");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        panel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 70, 30));

        Add.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 51, 51));
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        panel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 70, 30));

        delete.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 51, 51));
        delete.setText("Delete");
        delete.setActionCommand("");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        panel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 80, 30));

        email.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 0));
        email.setText("Email");
        panel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        panel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 160, 30));
        panel1.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 160, 30));

        gender.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 0));
        gender.setText("Gender");
        panel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Class");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));
        panel1.add(Class, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 160, 30));
        panel1.add(seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 160, 30));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Seat No");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Arrival");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Departure");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));
        panel1.add(departure, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 160, 30));
        panel1.add(arrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 160, 30));

        phone.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 0));
        phone.setText("Phone No");
        panel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));
        panel1.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 160, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setText("First Class Passengers");
        jLabel3.setToolTipText("");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setText("Karachi Airline Service");
        jLabel4.setToolTipText("");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 770, 50));

        exit.setBackground(new java.awt.Color(102, 102, 102));
        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 51));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        panel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, 50));

        Back.setBackground(new java.awt.Color(102, 102, 102));
        Back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 0, 51));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        panel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guman Singh\\OneDrive\\Documents\\NetBeansProjects\\airline\\pics\\architecture-bay-blue-sky-275582.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 1370, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDataVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tblDataVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataVetoableChange

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        if (ValidateFields()){
           model.insertRow(tblData.getRowCount(),new Object[]{
           name.getText(),
           age.getText(),
           Gender.getText(),
           Email.getText(),
           phone.getText(),
           seat.getText(),
           Class.getText(),
           departure.getText(),
           arrival.getText(),
           });
           resetField();
       }
    }//GEN-LAST:event_AddActionPerformed

    private void panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseClicked
        tblData.clearSelection();
    }//GEN-LAST:event_panel1MouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        model.removeRow(0);
    }//GEN-LAST:event_clearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       if (tblData.getSelectedRow()== -1){
          JOptionPane.showMessageDialog(firstClass.this,"Select any row first!");
          return;
        }
        model.removeRow(tblData.getSelectedRow());
    }//GEN-LAST:event_deleteActionPerformed
    private JFrame frame;
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        frame = new JFrame ("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Do you really want to Exit","Output Console",
            JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_NO_OPTION)){
        System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new ticketing().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstClass().setVisible(true);
            }
        });
    }
     private boolean ValidateFields(){
            if (name.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(firstClass.this,"Enter your Name!");
                name.grabFocus();
                return false;
            }
            if (age.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(firstClass.this,"Enter your Age!");
                age.grabFocus();
                return false;
        }
            if (Gender.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(firstClass.this,"Enter your Gender!");
                Gender.grabFocus();
                return false;
        }
            if (Email.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(firstClass.this,"Enter your Email!");
                Email.grabFocus();
                return false;
        }
            if (phone.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(firstClass.this,"Enter your Phone Number!");
                phone.grabFocus();
                return false;
        }
            if (seat.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(firstClass.this,"Enter your Seat Number!");
                seat.grabFocus();
                return false;
        }
            if (Class.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(firstClass.this,"Enter your Class!");
                Class.grabFocus();
                return false;
        }
            if (departure.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(firstClass.this,"Enter Departure City!");
                departure.grabFocus();
                return false;
        }
            if (arrival.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(firstClass.this,"Enter Arrival City!");
                arrival.grabFocus();
                return false;
        }
            return true;
        }
   private void resetField(){
       name.setText("");
       age.setText("");
       Gender.setText("");
       Email.setText("");
       phone.setText("");
       seat.setText("");
       Class.setText("");
       departure.setText("");
       arrival.setText("");
       
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel Age;
    private javax.swing.JButton Back;
    private javax.swing.JTextField Class;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField age;
    private javax.swing.JTextField arrival;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField departure;
    private javax.swing.JLabel email;
    private javax.swing.JButton exit;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name4;
    private java.awt.Panel panel1;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField seat;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
