
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gumansingh
 */
public class hotel extends javax.swing.JFrame {

    /**
     * Creates new form hotel
     */
    DefaultTableModel model;
    public hotel() {
        initComponents();
        setSize (1520, 750);
        model = (DefaultTableModel) tblData.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        panel2 = new java.awt.Panel();
        jLabel10 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        surname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        address = new javax.swing.JTextField();
        postal = new javax.swing.JComboBox();
        phone = new javax.swing.JTextField();
        nation = new javax.swing.JComboBox();
        dob = new com.toedter.calendar.JDateChooser();
        checkin = new com.toedter.calendar.JDateChooser();
        checkout = new com.toedter.calendar.JDateChooser();
        type = new javax.swing.JComboBox();
        room = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        Total = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        meal = new javax.swing.JComboBox();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        panel2.setBackground(new java.awt.Color(0, 102, 102));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Name");
        panel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Hotel Booking");
        panel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 270, -1));

        surname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel2.add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 170, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Surname");
        panel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        gender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gender.setText("Gender");
        panel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        Male.setBackground(new java.awt.Color(255, 102, 102));
        bg.add(Male);
        Male.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Male.setSelected(true);
        Male.setText("Male");
        Male.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        panel2.add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 80, 30));

        Female.setBackground(new java.awt.Color(255, 102, 102));
        bg.add(Female);
        Female.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Female.setText("Female");
        Female.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        panel2.add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 80, 30));

        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 170, 30));

        postal.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        postal.setForeground(new java.awt.Color(0, 153, 51));
        postal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "         Select Code", "54000", "55673", "87544", "87363", "76775", "39373", "35312", "53212", "22555", "14156", "15677", "86866", "24311", "42255", "58543", "25674", "36781", "42566", "13358", "89766", "23567", "23598", "45783", "35707" }));
        postal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel2.add(postal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 170, 30));

        phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 170, 30));

        nation.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nation.setForeground(new java.awt.Color(0, 153, 51));
        nation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "     Select Nationality", "Sindh (Sindhi)", "Punajb (Punjabi)", "Balochistan (Balochi)", "Afghanistan (Afghani)", "India (Indian)", "Iran (Irani)", "Italy (Italian)", "Spain (Spanish)", "Australia (Australian)", "America (American)", "UK (British)" }));
        nation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel2.add(nation, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 170, 30));

        dob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel2.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 170, 30));

        checkin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel2.add(checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 170, 30));

        checkout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel2.add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 170, 30));

        type.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        type.setForeground(new java.awt.Color(0, 153, 51));
        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "    Select Room Type", "Single Room", "Double Room", "Family Room" }));
        type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel2.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 170, 30));

        room.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        room.setForeground(new java.awt.Color(0, 153, 51));
        room.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "         Select Room", "466", "467", "468", "469", "470", "471", "472", "473", "474", "475", "476", "477", "478", "479", "480", " " }));
        room.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel2.add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Address");
        panel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Postal Code");
        panel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Mobile Number");
        panel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Nationality");
        panel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Date Of Birth");
        panel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Check In Date");
        panel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Check Out Date");
        panel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Room Type");
        panel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Room Number");
        panel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        panel2.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 80, 40));

        submit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        panel2.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 650, 80, 40));

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        panel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 650, 80, 40));

        tblData.setBackground(new java.awt.Color(204, 255, 204));
        tblData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Surname", "Gender", "Address", "Postal Code", "Phone No", "Email", "Nationality", "Date of Birth", "Check In", "Check Out", "Room Type", "Room No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.setAlignmentX(0.1F);
        tblData.setGridColor(new java.awt.Color(255, 255, 102));
        tblData.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblData);

        panel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 920, 840));

        delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        panel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, 80, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Email");
        panel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 170, 30));

        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panel2.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 100, 40));

        Total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Total.setText("Total");
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        panel2.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 80, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Meal");
        panel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        meal.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        meal.setForeground(new java.awt.Color(0, 153, 51));
        meal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "         Select Meal", "One Time", "Two Times", "Three Times" }));
        meal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel2.add(meal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 170, 30));

        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        panel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, 80, 40));

        getContentPane().add(panel2);
        panel2.setBounds(0, 0, 1370, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        gender.setText(Male.getText());
    }//GEN-LAST:event_MaleActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        gender.setText(Female.getText());
    }//GEN-LAST:event_FemaleActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       name.setText("");
       surname.setText("");
       phone.setText("");
       email.setText("");
       address.setText("");
       meal.setSelectedIndex(0);
       checkin.setDate(null);
       dob.setDate(null);
       checkout.setDate(null);
       postal.setSelectedIndex(0);
       nation.setSelectedIndex(0);
       type.setSelectedIndex(0);
       room.setSelectedIndex(0);
    }//GEN-LAST:event_resetActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        model.insertRow(tblData.getRowCount(),new Object[]{
        name.getText(),
        surname.getText(),
        gender.getText(),
        address.getText(),
        postal.getSelectedItem(),
        phone.getText(),
        email.getText(),
        nation.getSelectedItem(),
        dob.getDate(),
        checkin.getDate(),
        checkout.getDate(),
        type.getSelectedItem(),
        room.getSelectedItem(),
        });
        resetField();
    }//GEN-LAST:event_submitActionPerformed
    private JFrame frame;
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        frame = new JFrame ("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Do you want to Exit","Hotel Booking",
            JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_NO_OPTION)){
        System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       if (tblData.getSelectedRow()== -1){
          JOptionPane.showMessageDialog(null,"Select any row first!");
          return;
        }
        model.removeRow(tblData.getSelectedRow());
    }//GEN-LAST:event_deleteActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
    int single = 1000;
    int Double = 2000;
    int Family = 3000;
    int one = 500;
    int two = 1000;
    int three = 2000;
       String Single = type.getSelectedItem().toString();
       String Meal = meal.getSelectedItem().toString();
    if (Single.equals ("Single Room") && Meal.equals ("One Time")){
        total.setText(Integer.toString(single + one));
    }else if (Single.equals ("Single Room") && Meal.equals ("Two Times")){
        total.setText(Integer.toString(single + two));
    }else if (Single.equals ("Single Room") && Meal.equals ("Three Times")){
        total.setText(Integer.toString(single + three));
    }else if (Single.equals ("Double Room") && Meal.equals ("One Time")){
        total.setText(Integer.toString(Double + one));
    }else if (Single.equals ("Double Room") && Meal.equals ("Two Times")){
        total.setText(Integer.toString(Double + two));
    }else if (Single.equals ("Double Room") && Meal.equals ("Three Times")){
        total.setText(Integer.toString(Double + three));
    }   
    if (Single.equals ("Family Room") && Meal.equals ("One Time")){
        total.setText(Integer.toString(Family + one));
    }   
    if (Single.equals ("Family Room") && Meal.equals ("Two Times")){
        total.setText(Integer.toString(Family + two));
    }   
    if (Single.equals ("Family Room") && Meal.equals ("Three Times")){
        total.setText(Integer.toString(Family + three));
     }       
    }//GEN-LAST:event_TotalActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new ticketing().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotel().setVisible(true);
            }
        });
    }
        private void resetField(){
       name.setText("");
       surname.setText("");
       phone.setText("");
       email.setText("");
       address.setText("");
       meal.setSelectedIndex(0);
       checkin.setDate(null);
       dob.setDate(null);
       checkout.setDate(null);
       postal.setSelectedIndex(0);
       nation.setSelectedIndex(0);
       type.setSelectedIndex(0);
       room.setSelectedIndex(0);
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton Female;
    public javax.swing.JRadioButton Male;
    private javax.swing.JButton Total;
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup bg;
    private com.toedter.calendar.JDateChooser checkin;
    private com.toedter.calendar.JDateChooser checkout;
    private javax.swing.JButton delete;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JButton exit;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox meal;
    private javax.swing.JTextField name;
    public javax.swing.JComboBox nation;
    private java.awt.Panel panel2;
    private javax.swing.JTextField phone;
    public javax.swing.JComboBox postal;
    private javax.swing.JButton reset;
    public javax.swing.JComboBox room;
    private javax.swing.JButton submit;
    private javax.swing.JTextField surname;
    private javax.swing.JTable tblData;
    private javax.swing.JLabel total;
    public javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
}
