
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gumansingh
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setSize (1520, 750);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        login = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        remember = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setForeground(new java.awt.Color(51, 255, 0));
        setSize(new java.awt.Dimension(50, 30));
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(153, 255, 153));
        panel1.setForeground(new java.awt.Color(51, 255, 51));
        panel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 0));
        jLabel3.setText("Login Form");
        panel1.add(jLabel3);
        jLabel3.setBounds(1040, 50, 500, 130);

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("User Name");
        panel1.add(jLabel2);
        jLabel2.setBounds(830, 160, 190, 80);

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Password");
        panel1.add(jLabel1);
        jLabel1.setBounds(830, 240, 190, 90);

        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        panel1.add(username);
        username.setBounds(1060, 170, 280, 60);

        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel1.add(password);
        password.setBounds(1060, 260, 280, 60);

        register.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(153, 0, 153));
        register.setText("Register");
        register.setActionCommand("SignUp");
        register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel1.add(register);
        register.setBounds(860, 350, 140, 60);

        login.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(153, 0, 153));
        login.setText("LogIn");
        login.setActionCommand("Log In");
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        panel1.add(login);
        login.setBounds(1040, 350, 140, 60);

        reset.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(153, 0, 153));
        reset.setText("Reset");
        reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        panel1.add(reset);
        reset.setBounds(1220, 350, 120, 60);

        jLabel4.setBackground(new java.awt.Color(0, 204, 51));
        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Welcome to Karachi Airline Service");
        panel1.add(jLabel4);
        jLabel4.setBounds(250, 20, 870, 70);

        remember.setBackground(new java.awt.Color(255, 255, 0));
        remember.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        remember.setForeground(new java.awt.Color(255, 0, 51));
        remember.setText("Remember Me");
        remember.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panel1.add(remember);
        remember.setBounds(810, 420, 140, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guman Singh\\OneDrive\\Documents\\NetBeansProjects\\airline\\pics\\LOGon.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        panel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 1380, 750);

        getContentPane().add(panel1);
        panel1.setBounds(0, -30, 1370, 750);

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-220, 10, 1580, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       username.setText("");
       password.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String uname = username.getText();
       String pass = password.getText();
       if (uname.equals ("guman") && (pass.equals ("1234"))){
           JOptionPane.showMessageDialog(login.this,"Login Successful");
           
           new ticketing().setVisible(true);
    
       }else{
           JOptionPane.showMessageDialog(null,"Incorrect Password");
           username.setText(null);
           password.setText(null);
       }
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        splash s = new splash();
        s.setVisible(true);
        try{
            for (int i= 0; i<= 100; i++){
                Thread.sleep(20);
                s.print.setText(Integer.toString(i)+ "%");
                s.pb1.setValue(i);
                s.pb2.setValue(i);  
                if (i==100){
                    s.setVisible(true);
                }
            }
            s.setVisible(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton login;
    private java.awt.Panel panel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton register;
    private javax.swing.JCheckBox remember;
    private javax.swing.JButton reset;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
