
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gumansingh
 */
public class OutputConsole extends javax.swing.JFrame {

    /**
     * Creates new form OutputConsole
     */
    public OutputConsole() {
        initComponents();
        setSize (1520, 750);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        age = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        city2 = new javax.swing.JLabel();
        city1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        pname = new javax.swing.JLabel();
        page = new javax.swing.JLabel();
        pgender = new javax.swing.JLabel();
        paddress = new javax.swing.JLabel();
        pemail = new javax.swing.JLabel();
        pphone = new javax.swing.JLabel();
        pseat = new javax.swing.JLabel();
        pdeparture = new javax.swing.JLabel();
        parrival = new javax.swing.JLabel();
        pdepart = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        city4 = new javax.swing.JLabel();
        pclass = new javax.swing.JLabel();
        city5 = new javax.swing.JLabel();
        preturn = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(102, 255, 102));
        panel1.setLayout(null);

        age.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 0));
        age.setText("Age");
        panel1.add(age);
        age.setBounds(30, 170, 150, 33);

        gender.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 0));
        gender.setText("Gender");
        panel1.add(gender);
        gender.setBounds(30, 220, 180, 33);

        name3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        name3.setForeground(new java.awt.Color(255, 255, 0));
        name3.setText("Address");
        panel1.add(name3);
        name3.setBounds(30, 270, 180, 33);

        name1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 0));
        name1.setText("Phone No");
        panel1.add(name1);
        name1.setBounds(30, 370, 190, 33);

        name2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        name2.setForeground(new java.awt.Color(255, 255, 0));
        name2.setText("Seat No");
        panel1.add(name2);
        name2.setBounds(30, 420, 180, 33);

        city.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 0));
        city.setText("Class");
        panel1.add(city);
        city.setBounds(30, 470, 200, 33);

        city2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        city2.setForeground(new java.awt.Color(255, 255, 0));
        city2.setText("Arrival");
        panel1.add(city2);
        city2.setBounds(30, 570, 170, 33);

        city1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        city1.setForeground(new java.awt.Color(255, 255, 0));
        city1.setText("Depart Date");
        panel1.add(city1);
        city1.setBounds(30, 620, 210, 33);

        name.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 0));
        name.setText("Name");
        panel1.add(name);
        name.setBounds(30, 120, 180, 30);

        jLabel8.setBackground(new java.awt.Color(204, 255, 0));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("Karachi Airline Service");
        panel1.add(jLabel8);
        jLabel8.setBounds(380, 0, 640, 80);

        name4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        name4.setForeground(new java.awt.Color(255, 255, 0));
        name4.setText("Email");
        panel1.add(name4);
        name4.setBounds(30, 320, 160, 33);

        pname.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        pname.setForeground(new java.awt.Color(0, 255, 0));
        panel1.add(pname);
        pname.setBounds(220, 120, 310, 30);

        page.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        page.setForeground(new java.awt.Color(0, 255, 0));
        panel1.add(page);
        page.setBounds(220, 170, 290, 30);

        pgender.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        pgender.setForeground(new java.awt.Color(0, 255, 0));
        panel1.add(pgender);
        pgender.setBounds(220, 220, 310, 30);

        paddress.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        paddress.setForeground(new java.awt.Color(0, 255, 0));
        panel1.add(paddress);
        paddress.setBounds(220, 270, 320, 30);

        pemail.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        pemail.setForeground(new java.awt.Color(0, 255, 0));
        panel1.add(pemail);
        pemail.setBounds(220, 320, 300, 30);

        pphone.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        pphone.setForeground(new java.awt.Color(0, 255, 0));
        panel1.add(pphone);
        pphone.setBounds(220, 370, 320, 30);

        pseat.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        pseat.setForeground(new java.awt.Color(0, 255, 0));
        panel1.add(pseat);
        pseat.setBounds(220, 420, 320, 30);

        pdeparture.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        pdeparture.setForeground(new java.awt.Color(0, 255, 0));
        panel1.add(pdeparture);
        pdeparture.setBounds(220, 520, 330, 30);

        parrival.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        parrival.setForeground(new java.awt.Color(0, 255, 0));
        panel1.add(parrival);
        parrival.setBounds(220, 570, 310, 30);

        pdepart.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        pdepart.setForeground(new java.awt.Color(0, 255, 0));
        panel1.add(pdepart);
        pdepart.setBounds(220, 620, 580, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 255));
        jLabel9.setText("Booking Information");
        panel1.add(jLabel9);
        jLabel9.setBounds(90, 80, 450, 50);

        city4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        city4.setForeground(new java.awt.Color(255, 255, 0));
        city4.setText("Departure");
        panel1.add(city4);
        city4.setBounds(30, 520, 200, 33);

        pclass.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        pclass.setForeground(new java.awt.Color(0, 255, 0));
        panel1.add(pclass);
        pclass.setBounds(220, 470, 330, 30);

        city5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        city5.setForeground(new java.awt.Color(255, 255, 0));
        city5.setText("Return Date");
        panel1.add(city5);
        city5.setBounds(30, 670, 210, 33);

        preturn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        preturn.setForeground(new java.awt.Color(0, 255, 0));
        panel1.add(preturn);
        preturn.setBounds(220, 670, 580, 30);

        exit.setBackground(new java.awt.Color(255, 102, 255));
        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(51, 0, 204));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        panel1.add(exit);
        exit.setBounds(370, 710, 90, 50);

        Back.setBackground(new java.awt.Color(255, 102, 255));
        Back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(51, 0, 204));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        panel1.add(Back);
        Back.setBounds(240, 710, 90, 50);

        Next.setBackground(new java.awt.Color(255, 102, 255));
        Next.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Next.setForeground(new java.awt.Color(51, 0, 204));
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        panel1.add(Next);
        Next.setBounds(500, 710, 90, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guman Singh\\OneDrive\\Documents\\NetBeansProjects\\airline\\pics\\output console.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        panel1.add(jLabel2);
        jLabel2.setBounds(4, -6, 1420, 780);

        getContentPane().add(panel1);
        panel1.setBounds(-6, -1, 1420, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new ticketing().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed
    private JFrame frame;
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        frame = new JFrame ("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Do you really want to Exit","Output Console",
            JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_NO_OPTION)){
        System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
       frame = new JFrame ("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Do you really want to Book a Hotel","Hotel Booking",
            JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_NO_OPTION)){
        new hotel().setVisible(true);
        } 
    }//GEN-LAST:event_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutputConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutputConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutputConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutputConsole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Next;
    private javax.swing.JLabel age;
    private javax.swing.JLabel city;
    private javax.swing.JLabel city1;
    private javax.swing.JLabel city2;
    private javax.swing.JLabel city4;
    private javax.swing.JLabel city5;
    private javax.swing.JButton exit;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    public javax.swing.JLabel paddress;
    public javax.swing.JLabel page;
    private java.awt.Panel panel1;
    public javax.swing.JLabel parrival;
    public javax.swing.JLabel pclass;
    public javax.swing.JLabel pdepart;
    public javax.swing.JLabel pdeparture;
    public javax.swing.JLabel pemail;
    public javax.swing.JLabel pgender;
    public javax.swing.JLabel pname;
    public javax.swing.JLabel pphone;
    public javax.swing.JLabel preturn;
    public javax.swing.JLabel pseat;
    // End of variables declaration//GEN-END:variables
}
