
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gumansingh
 */
public class quiz extends javax.swing.JFrame {

    /**
     * Creates new form quiz
     */
    public quiz() {
        initComponents();
        setSize (1520, 750);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        bg2 = new javax.swing.ButtonGroup();
        bg3 = new javax.swing.ButtonGroup();
        bg4 = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        print = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        guman = new javax.swing.JRadioButton();
        ambreen = new javax.swing.JRadioButton();
        not = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        amb = new javax.swing.JRadioButton();
        kash = new javax.swing.JRadioButton();
        mohib = new javax.swing.JRadioButton();
        hassan1 = new javax.swing.JRadioButton();
        jabar = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        guman1 = new javax.swing.JRadioButton();
        ambreen1 = new javax.swing.JRadioButton();
        hassan2 = new javax.swing.JRadioButton();
        not1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        amb1 = new javax.swing.JRadioButton();
        kash1 = new javax.swing.JRadioButton();
        mohib1 = new javax.swing.JRadioButton();
        jabar1 = new javax.swing.JRadioButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(0, 102, 102));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panel1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 160, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Q1: Who created this program?");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 430, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Quiz");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 110, 50));

        bg.add(guman);
        guman.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        guman.setForeground(new java.awt.Color(204, 0, 204));
        guman.setText("Guman Singh");
        guman.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        guman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumanActionPerformed(evt);
            }
        });
        panel1.add(guman, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 120, -1));

        bg.add(ambreen);
        ambreen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ambreen.setForeground(new java.awt.Color(204, 0, 204));
        ambreen.setText("Ambreen Malik");
        ambreen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ambreenItemStateChanged(evt);
            }
        });
        ambreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambreenActionPerformed(evt);
            }
        });
        panel1.add(ambreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 120, -1));

        bg.add(not);
        not.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        not.setForeground(new java.awt.Color(204, 0, 204));
        not.setText("NOT");
        not.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notActionPerformed(evt);
            }
        });
        panel1.add(not, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Q2: Who are the co-developers of this program?");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 590, 30));

        bg2.add(amb);
        amb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        amb.setForeground(new java.awt.Color(255, 0, 51));
        amb.setText("Kashif & Jarnail");
        amb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambActionPerformed(evt);
            }
        });
        panel1.add(amb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 150, -1));

        bg2.add(kash);
        kash.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kash.setForeground(new java.awt.Color(255, 0, 51));
        kash.setText("Ambreen & Hassan");
        kash.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kashItemStateChanged(evt);
            }
        });
        kash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kashActionPerformed(evt);
            }
        });
        panel1.add(kash, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 150, -1));

        bg2.add(mohib);
        mohib.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mohib.setForeground(new java.awt.Color(255, 0, 51));
        mohib.setText("Mohib & Manish");
        mohib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mohibActionPerformed(evt);
            }
        });
        panel1.add(mohib, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 150, -1));

        bg.add(hassan1);
        hassan1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hassan1.setForeground(new java.awt.Color(204, 0, 204));
        hassan1.setText("Hassan Jamil");
        hassan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hassan1ActionPerformed(evt);
            }
        });
        panel1.add(hassan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 120, -1));

        bg2.add(jabar);
        jabar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jabar.setForeground(new java.awt.Color(255, 0, 51));
        jabar.setText("Jabbar & Huzaifa");
        jabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabarActionPerformed(evt);
            }
        });
        panel1.add(jabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 150, -1));

        submit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submit.setForeground(new java.awt.Color(51, 0, 255));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        panel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, 120, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 204));
        jLabel6.setText("Q3: What is the name of this Airline Service?");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 560, 30));

        bg3.add(guman1);
        guman1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        guman1.setForeground(new java.awt.Color(0, 51, 51));
        guman1.setText("Asgard Airline Service");
        guman1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        guman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guman1ActionPerformed(evt);
            }
        });
        panel1.add(guman1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 180, 30));

        bg3.add(ambreen1);
        ambreen1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ambreen1.setForeground(new java.awt.Color(0, 51, 51));
        ambreen1.setText("Avalon Airline Service");
        ambreen1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ambreen1ItemStateChanged(evt);
            }
        });
        ambreen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambreen1ActionPerformed(evt);
            }
        });
        panel1.add(ambreen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 170, 30));

        bg3.add(hassan2);
        hassan2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hassan2.setForeground(new java.awt.Color(0, 51, 51));
        hassan2.setText("Fly Karachi Airline Service");
        hassan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hassan2ActionPerformed(evt);
            }
        });
        panel1.add(hassan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 180, 30));

        bg3.add(not1);
        not1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        not1.setForeground(new java.awt.Color(0, 51, 51));
        not1.setText("Karachi Airline Service");
        not1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                not1ActionPerformed(evt);
            }
        });
        panel1.add(not1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 170, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Q4: What is the surname of the creator of this program?");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 690, 30));

        bg4.add(amb1);
        amb1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        amb1.setForeground(new java.awt.Color(102, 153, 0));
        amb1.setText("Rathore");
        amb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amb1ActionPerformed(evt);
            }
        });
        panel1.add(amb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 150, -1));

        bg4.add(kash1);
        kash1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kash1.setForeground(new java.awt.Color(102, 153, 0));
        kash1.setText("Thakur");
        kash1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kash1ItemStateChanged(evt);
            }
        });
        kash1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kash1ActionPerformed(evt);
            }
        });
        panel1.add(kash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 150, -1));

        bg4.add(mohib1);
        mohib1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mohib1.setForeground(new java.awt.Color(102, 153, 0));
        mohib1.setText("Both b & c");
        mohib1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mohib1ActionPerformed(evt);
            }
        });
        panel1.add(mohib1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 150, -1));

        bg4.add(jabar1);
        jabar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jabar1.setForeground(new java.awt.Color(102, 153, 0));
        jabar1.setText("Singh");
        jabar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabar1ActionPerformed(evt);
            }
        });
        panel1.add(jabar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 150, -1));

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(51, 0, 255));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        panel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 120, 50));

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 1400, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gumanActionPerformed
        String g = guman.getText();
    }//GEN-LAST:event_gumanActionPerformed

    private void ambreenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ambreenItemStateChanged

    }//GEN-LAST:event_ambreenItemStateChanged

    private void ambreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambreenActionPerformed
        String a = ambreen.getText();
    }//GEN-LAST:event_ambreenActionPerformed

    private void notActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notActionPerformed

    }//GEN-LAST:event_notActionPerformed

    private void ambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambActionPerformed
        String h = amb.getText();
    }//GEN-LAST:event_ambActionPerformed

    private void kashItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kashItemStateChanged
        String h = kash.getText();
    }//GEN-LAST:event_kashItemStateChanged

    private void kashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kashActionPerformed

    private void mohibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mohibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mohibActionPerformed

    private void hassan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hassan1ActionPerformed
        String h = hassan1.getText();
    }//GEN-LAST:event_hassan1ActionPerformed

    private void jabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabarActionPerformed
        String h = jabar.getText();
    }//GEN-LAST:event_jabarActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if (guman.isSelected() &&  kash.isSelected() &&  not1.isSelected() &&  mohib1.isSelected()) {
            Random rand = new Random();
            int n = rand.nextInt(30);
            n += 1;
            String val = String.valueOf(n);
            print.setText(val);
        }else{
            JOptionPane.showMessageDialog(null,"Cann't generate Promo Code\nGuman Singh\nAmbreen & Hassan\nKarachi Airline Service\nSingh & Thakur");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void guman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guman1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guman1ActionPerformed

    private void ambreen1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ambreen1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ambreen1ItemStateChanged

    private void ambreen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambreen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ambreen1ActionPerformed

    private void hassan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hassan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hassan2ActionPerformed

    private void not1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_not1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_not1ActionPerformed

    private void amb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amb1ActionPerformed

    private void kash1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kash1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_kash1ItemStateChanged

    private void kash1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kash1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kash1ActionPerformed

    private void mohib1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mohib1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mohib1ActionPerformed

    private void jabar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jabar1ActionPerformed
    private JFrame frame;
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
       frame = new JFrame ("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Do you really want to Exit","Output Console",
            JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_NO_OPTION)){
        System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton amb;
    private javax.swing.JRadioButton amb1;
    private javax.swing.JRadioButton ambreen;
    private javax.swing.JRadioButton ambreen1;
    private javax.swing.ButtonGroup bg;
    private javax.swing.ButtonGroup bg2;
    private javax.swing.ButtonGroup bg3;
    private javax.swing.ButtonGroup bg4;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton guman;
    private javax.swing.JRadioButton guman1;
    private javax.swing.JRadioButton hassan1;
    private javax.swing.JRadioButton hassan2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jabar;
    private javax.swing.JRadioButton jabar1;
    private javax.swing.JRadioButton kash;
    private javax.swing.JRadioButton kash1;
    private javax.swing.JRadioButton mohib;
    private javax.swing.JRadioButton mohib1;
    private javax.swing.JRadioButton not;
    private javax.swing.JRadioButton not1;
    private java.awt.Panel panel1;
    private javax.swing.JLabel print;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
