
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gumansingh
 */
public class ticketing extends javax.swing.JFrame {

    /**
     * Creates new form ticketing
     */
    public ticketing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        label = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        abc = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        xname = new javax.swing.JTextPane();
        city = new javax.swing.JLabel();
        xclass = new javax.swing.JComboBox();
        age = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        xage = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        xphone = new javax.swing.JTextPane();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        xaddress = new javax.swing.JTextPane();
        name3 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        xemail = new javax.swing.JTextPane();
        name4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        city1 = new javax.swing.JLabel();
        xarrival = new javax.swing.JComboBox();
        city2 = new javax.swing.JLabel();
        xdepartdate = new com.toedter.calendar.JDateChooser();
        city3 = new javax.swing.JLabel();
        xreturndate = new com.toedter.calendar.JDateChooser();
        agree = new javax.swing.JCheckBox();
        reset = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        name5 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        xseat = new javax.swing.JTextPane();
        xdepart = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        store = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        close = new javax.swing.JMenuItem();
        precords = new javax.swing.JMenu();
        first = new javax.swing.JMenuItem();
        business = new javax.swing.JMenuItem();
        premium = new javax.swing.JMenuItem();
        economy = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        flight = new javax.swing.JMenu();
        arrival = new javax.swing.JMenuItem();
        departure = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        available = new javax.swing.JMenu();
        AFlight = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Quiz = new javax.swing.JMenu();
        quiz = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        hotel = new javax.swing.JMenuItem();

        jScrollPane3.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setForeground(new java.awt.Color(204, 255, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setBackground(new java.awt.Color(51, 255, 51));
        label.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 48)); // NOI18N
        label.setForeground(new java.awt.Color(204, 204, 0));
        label.setText("Karachi Airline Service");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 560, 50));

        name.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(204, 204, 0));
        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 60, -1));

        abc.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        abc.setForeground(new java.awt.Color(204, 204, 0));
        abc.setText("Gender");
        getContentPane().add(abc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 70, -1));

        jScrollPane4.setForeground(new java.awt.Color(51, 255, 51));

        xname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        xname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                xnameKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(xname);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 170, 30));

        city.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        city.setForeground(new java.awt.Color(204, 204, 0));
        city.setText("Departure");
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 80, -1));

        xclass.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        xclass.setForeground(new java.awt.Color(0, 153, 51));
        xclass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "         Select Class", "First Class", "Business Class", "Premium Class", "Economy Class" }));
        xclass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        xclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xclassActionPerformed(evt);
            }
        });
        getContentPane().add(xclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 170, 30));

        age.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        age.setForeground(new java.awt.Color(204, 204, 0));
        age.setText("Age");
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 40, -1));

        Male.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(Male);
        Male.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Male.setForeground(new java.awt.Color(255, 255, 255));
        Male.setSelected(true);
        Male.setText("Male");
        Male.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        getContentPane().add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 80, 30));

        Female.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(Female);
        Female.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Female.setForeground(new java.awt.Color(255, 255, 255));
        Female.setText("Female");
        Female.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        getContentPane().add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 80, 30));

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 14)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 330, -1));

        xage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        xage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                xageKeyTyped(evt);
            }
        });
        jScrollPane11.setViewportView(xage);

        getContentPane().add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 170, 30));

        jScrollPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane5.setForeground(new java.awt.Color(51, 255, 51));
        jScrollPane5.setViewportView(xphone);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 170, 30));

        name1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        name1.setForeground(new java.awt.Color(204, 204, 0));
        name1.setText("Phone No");
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 70, -1));

        name2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        name2.setForeground(new java.awt.Color(204, 204, 0));
        name2.setText("Seat No");
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 60, -1));

        jScrollPane7.setForeground(new java.awt.Color(51, 255, 51));

        xaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane7.setViewportView(xaddress);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 170, 30));

        name3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        name3.setForeground(new java.awt.Color(204, 204, 0));
        name3.setText("Address");
        getContentPane().add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 60, -1));

        jScrollPane8.setForeground(new java.awt.Color(51, 255, 51));

        xemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane8.setViewportView(xemail);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 170, 30));

        name4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        name4.setForeground(new java.awt.Color(204, 204, 0));
        name4.setText("Email");
        getContentPane().add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 60, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 102));
        jLabel3.setText("Passenger Information");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 210, 40));

        city1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        city1.setForeground(new java.awt.Color(204, 204, 0));
        city1.setText("Depart Date");
        getContentPane().add(city1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 120, -1));

        xarrival.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        xarrival.setForeground(new java.awt.Color(0, 153, 51));
        xarrival.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "           Select City", "Karachi", "Lahore ", "Islamabad", "Sukkur", "Mithi", "Kertee", "Larkana", "Umerkot", "Quetta", "Peshawar", "Rome", "Venice", "Sydney", "Austria", "New York", "Washington DC", "California", "Ankara", "Khatmandu", "Kolkata", "New Delhi", "Mumbai", "Chennai", "Jaipur", "Ahemadabad", "Surat", "Lucknow", " " }));
        xarrival.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(xarrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 170, 30));

        city2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        city2.setForeground(new java.awt.Color(204, 204, 0));
        city2.setText("Arrival");
        getContentPane().add(city2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 80, 20));

        xdepartdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        xdepartdate.setDateFormatString("d, MMM , yyyy");
        xdepartdate.setIcon(null);
        getContentPane().add(xdepartdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 170, 30));

        city3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        city3.setForeground(new java.awt.Color(204, 204, 0));
        city3.setText("Return Date");
        getContentPane().add(city3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 120, -1));

        xreturndate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        xreturndate.setDateFormatString("d, MMM , yyyy");
        getContentPane().add(xreturndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 170, 30));

        agree.setBackground(new java.awt.Color(0, 51, 51));
        agree.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        agree.setForeground(new java.awt.Color(255, 255, 255));
        agree.setText("I have read and agree to the Terms and Conditions");
        getContentPane().add(agree, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 380, 50));

        reset.setBackground(new java.awt.Color(0, 204, 51));
        reset.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(102, 51, 0));
        reset.setText("Reset");
        reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 3));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 90, 40));

        submit.setBackground(new java.awt.Color(0, 204, 51));
        submit.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(102, 51, 0));
        submit.setText("Submit");
        submit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 3));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 90, 40));

        name5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        name5.setForeground(new java.awt.Color(204, 204, 0));
        name5.setText("Class");
        getContentPane().add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 60, -1));

        jScrollPane10.setForeground(new java.awt.Color(51, 255, 51));

        xseat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane10.setViewportView(xseat);

        getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 170, 30));

        xdepart.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        xdepart.setForeground(new java.awt.Color(0, 153, 51));
        xdepart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "           Select City", "Karachi", "Lahore ", "Islamabad", "Sukkur", "Mithi", "Kertee", "Larkana", "Umerkot", "Quetta", "Peshawar", "Rome", "Venice", "Sydney", "Austria", "New York", "Washington DC", "California", "Ankara", "Khatmandu", "Kolkata", "New Delhi", "Mumbai", "Chennai", "Jaipur", "Ahemadabad", "Surat", "Lucknow", " " }));
        xdepart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        xdepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xdepartActionPerformed(evt);
            }
        });
        getContentPane().add(xdepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 170, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 102));
        jLabel5.setText("Booking Information");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 210, 40));

        exit.setBackground(new java.awt.Color(0, 204, 51));
        exit.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(102, 51, 0));
        exit.setText("Exit");
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 3));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 90, 40));

        store.setText("jLabel4");
        getContentPane().add(store, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, -1, -1));

        gender.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guman Singh\\OneDrive\\Documents\\NetBeansProjects\\airline\\pics\\menu consle.jpg")); // NOI18N
        gender.setText("jLabel2");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, -1, -1));

        jMenu1.setText("File");

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        open.setText("Open File");
        jMenu1.add(open);

        close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        close.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guman Singh\\OneDrive\\Documents\\NetBeansProjects\\airline\\pics\\open ile.png")); // NOI18N
        close.setText("Close File");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jMenu1.add(close);

        jMenuBar1.add(jMenu1);

        precords.setText("Passenger Records");

        first.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        first.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guman Singh\\OneDrive\\Documents\\NetBeansProjects\\airline\\pics\\save all016.png")); // NOI18N
        first.setText("First Class");
        first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstActionPerformed(evt);
            }
        });
        precords.add(first);

        business.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        business.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guman Singh\\OneDrive\\Documents\\NetBeansProjects\\airline\\pics\\abouts-applications-internet-icon.png")); // NOI18N
        business.setText("Business Class");
        business.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessActionPerformed(evt);
            }
        });
        precords.add(business);

        premium.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        premium.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guman Singh\\OneDrive\\Documents\\NetBeansProjects\\airline\\pics\\Applications-icon.png")); // NOI18N
        premium.setText("Premium Class");
        precords.add(premium);

        economy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        economy.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guman Singh\\OneDrive\\Documents\\NetBeansProjects\\airline\\pics\\empty dustbin016.png")); // NOI18N
        economy.setText("Economy Class");
        economy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economyActionPerformed(evt);
            }
        });
        precords.add(economy);
        precords.add(jSeparator2);

        jMenuBar1.add(precords);

        flight.setText("Flight Status");

        arrival.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        arrival.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guman Singh\\OneDrive\\Documents\\NetBeansProjects\\airline\\pics\\check file016.png")); // NOI18N
        arrival.setText("Arrival");
        arrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalActionPerformed(evt);
            }
        });
        flight.add(arrival);

        departure.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        departure.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guman Singh\\OneDrive\\Documents\\NetBeansProjects\\airline\\pics\\Apps-system-software-update-icon.png")); // NOI18N
        departure.setText("Departure");
        departure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureActionPerformed(evt);
            }
        });
        flight.add(departure);
        flight.add(jSeparator1);

        jMenuBar1.add(flight);

        available.setText("Availabe Flights");
        available.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                availableMouseEntered(evt);
            }
        });

        AFlight.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        AFlight.setText("Available Flights");
        AFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFlightActionPerformed(evt);
            }
        });
        available.add(AFlight);

        jMenuBar1.add(available);

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });

        About.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        About.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guman Singh\\OneDrive\\Documents\\NetBeansProjects\\airline\\pics\\about.png")); // NOI18N
        About.setText("About");
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AboutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AboutMouseReleased(evt);
            }
        });
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        about.add(About);

        jMenu3.setText("Developers");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Guman Singh");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Ambreen Malik");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Hassan Jamil");
        jMenu3.add(jMenuItem3);

        about.add(jMenu3);

        jMenuBar1.add(about);

        Quiz.setText("Quiz");

        quiz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        quiz.setText("Quiz");
        quiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizActionPerformed(evt);
            }
        });
        Quiz.add(quiz);

        jMenuBar1.add(Quiz);

        jMenu2.setText("Hotel");

        hotel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        hotel.setText("Hotel Booking");
        hotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelActionPerformed(evt);
            }
        });
        jMenu2.add(hotel);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
         gender.setText(Male.getText());
    }//GEN-LAST:event_MaleActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
         gender.setText(Female.getText());
    }//GEN-LAST:event_FemaleActionPerformed

    private void economyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_economyActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
     xname.setText("");
     xage.setText("");
     abc.setText("");
     xaddress.setText("");
     xemail.setText("");
     xphone.setText("");
     xseat.setText("");    
     xdepartdate.setDate(null);
     xreturndate.setDate(null);
     xclass.setSelectedIndex(0);
     xdepart.setSelectedIndex(0);
     xarrival.setSelectedIndex(0);
    }//GEN-LAST:event_resetActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if (ValidateFields()){
        OutputConsole o = new OutputConsole();
        o.pname.setText(xname.getText());
        o.page.setText(xage.getText());
        o.pgender.setText(gender.getText());
        o.paddress.setText(xaddress.getText());
        o.pemail.setText(xemail.getText());
        o.pphone.setText(xphone.getText());
        o.pseat.setText(xseat.getText());
        o.pclass.setText(store.getText());
        o.pdeparture.setText(xdepart.getSelectedItem().toString());
        o.parrival.setText(xarrival.getSelectedItem().toString());
        o.pdepart.setText(xdepartdate.getDate().toString());
        o.preturn.setText(xreturndate.getDate().toString());
        resetField();
        o.setVisible(true);
        }
    }//GEN-LAST:event_submitActionPerformed
    
    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
       System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
       
    }//GEN-LAST:event_aboutActionPerformed

    private void departureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureActionPerformed
        new departure().setVisible(true);
    }//GEN-LAST:event_departureActionPerformed
    
    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        new about().setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed

    private void firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstActionPerformed
        new firstClass().setVisible(true);
    }//GEN-LAST:event_firstActionPerformed

    private void xageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xageKeyTyped
        char ch = evt.getKeyChar();
        if(!((Character.isDigit(ch))))
            evt.consume();
    }//GEN-LAST:event_xageKeyTyped

    private void xnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xnameKeyTyped
       char ch = evt.getKeyChar();
        if(!(Character.isAlphabetic(ch)))
            evt.consume();
    }//GEN-LAST:event_xnameKeyTyped
    private void xphoneKeyTyped(java.awt.event.KeyEvent evt) {                              
        char ch = evt.getKeyChar();
        if(!((Character.isDigit(ch))))
            evt.consume();
    } 
    private void arrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalActionPerformed
      new Arivel().setVisible(true);
    }//GEN-LAST:event_arrivalActionPerformed

    private void xdepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xdepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xdepartActionPerformed

    private void AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseExited
       JOptionPane.showMessageDialog(ticketing.this,"Kiun ab nhi jana about mein?");
    }//GEN-LAST:event_AboutMouseExited

    private void AboutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseReleased
       //JOptionPane.showMessageDialog(ticketing.this,"Kya hai, Chalana nhi aata kya?");
    }//GEN-LAST:event_AboutMouseReleased

    private void AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseEntered
    }//GEN-LAST:event_AboutMouseEntered

    private void AboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMousePressed
      
    }//GEN-LAST:event_AboutMousePressed

    private void availableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availableMouseEntered
        //JOptionPane.showMessageDialog(ticketing.this,"Ispe click karo tabhi khulega!");
    }//GEN-LAST:event_availableMouseEntered

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
        
    }//GEN-LAST:event_AboutMouseClicked

    private void quizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizActionPerformed
        new quiz().setVisible(true);
    }//GEN-LAST:event_quizActionPerformed

    private void hotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelActionPerformed
        new hotel().setVisible(true);
    }//GEN-LAST:event_hotelActionPerformed
    private JFrame frame;
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        frame = new JFrame ("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Do you really want to Exit","Main Menu",
            JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_NO_OPTION)){
        System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void xclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xclassActionPerformed
        int First = 5000;
        int Business = 4000;
        int Premium = 3000;
        int Economy = 2000;
        if (xclass.getSelectedItem().toString().equals("First Class")){       
    frame = new JFrame("Exit");  
    if (JOptionPane.showInputDialog(frame,"Enter your Credit Card Number!","Input",
       JOptionPane.YES_NO_OPTION) .equals ("12")){
        if(JOptionPane.showConfirmDialog(frame,"Do you want to Continue!","Confirm",
           JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_NO_OPTION)){
            JOptionPane.showMessageDialog(null,"First Class Ticket purchased Successfully");
            store.setText(Integer.toString(First));
       }else{
            System.exit(0);
        }
    }else{
        JOptionPane.showMessageDialog(null,"Invalid Credit Card Number");
   }
    }else if (xclass.getSelectedItem().toString().equals("Business Class")){       
    frame = new JFrame("Exit");  
    if (JOptionPane.showInputDialog(frame,"Enter your Credit Card Number!","Input",
       JOptionPane.YES_NO_OPTION) .equals ("12")){
        if(JOptionPane.showConfirmDialog(frame,"Do you want to Continue!","Confirm",
           JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_NO_OPTION)){
            JOptionPane.showMessageDialog(null,"Business Class Ticket purchased Successfully");
            store.setText(Integer.toString(Business));
       }else{
            System.exit(0);
        }
    }else{
        JOptionPane.showMessageDialog(null,"Invalid Credit Card Number");
   }
    }//GEN-LAST:event_xclassActionPerformed
     else if (xclass.getSelectedItem().toString().equals("Premium Class")){       
    frame = new JFrame("Exit");  
    if (JOptionPane.showInputDialog(frame,"Enter your Credit Card Number!","Input",
       JOptionPane.YES_NO_OPTION) .equals ("12")){
        if(JOptionPane.showConfirmDialog(frame,"Do you want to Continue!","Confirm",
           JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_NO_OPTION)){
            JOptionPane.showMessageDialog(null,"Premim Class Ticket purchased Successfully");
            store.setText(Integer.toString(Premium));
       }else{
            System.exit(0);
        }
        
    }else{
        JOptionPane.showMessageDialog(null,"Invalid Credit Card Number");
   }
        }
        else if (xclass.getSelectedItem().toString().equals("Economy Class")){       
    frame = new JFrame("Exit");  
    if (JOptionPane.showInputDialog(frame,"Enter your Credit Card Number!","Input",
       JOptionPane.YES_NO_OPTION) .equals ("12")){
        if(JOptionPane.showConfirmDialog(frame,"Do you want to Continue!","Confirm",
           JOptionPane.YES_NO_OPTION) == (JOptionPane.YES_NO_OPTION)){
            JOptionPane.showMessageDialog(null,"Economy Class Ticket purchased Successfully");
            store.setText(Integer.toString(Economy));
       }else{
            System.exit(0);
        }
    }else{
        JOptionPane.showMessageDialog(null,"Invalid Credit Card Number");
   }
    }
    }
    private void AFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFlightActionPerformed
       new availableFlights().setVisible(true);
    }//GEN-LAST:event_AFlightActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void businessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessActionPerformed
       new business().setVisible(true);
    }//GEN-LAST:event_businessActionPerformed
    
                      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticketing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticketing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticketing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticketing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticketing().setVisible(true);
            }
        });
    }
      private boolean ValidateFields(){
            if (name.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(ticketing.this,"Enter your Name!");
                name.grabFocus();
                return false;
            }
            if (age.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(ticketing.this,"Enter your Age!");
                age.grabFocus();
                return false;
        }
            if (abc.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(ticketing.this,"Enter your Gender!");
                abc.grabFocus();
                return false;
        }
            if (xemail.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(ticketing.this,"Enter your Email!");
                xemail.grabFocus();
                return false;
        }
            if (xphone.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(ticketing.this,"Enter your Phone Number!");
                xphone.grabFocus();
                return false;
        }
            if (xseat.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(ticketing.this,"Enter your Seat Number!");
                xseat.grabFocus();
                return false;
        }
            return true;
        }
   private void resetField(){
       xname.setText("");
       xage.setText("");
       abc.setText("");
       xaddress.setText("");
       xemail.setText("");
       xphone.setText("");
       xseat.setText(""); 
       
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AFlight;
    private javax.swing.JMenuItem About;
    public javax.swing.JRadioButton Female;
    public javax.swing.JRadioButton Male;
    private javax.swing.JMenu Quiz;
    public javax.swing.JLabel abc;
    private javax.swing.JMenu about;
    private javax.swing.JLabel age;
    private javax.swing.JCheckBox agree;
    private javax.swing.JMenuItem arrival;
    private javax.swing.JMenu available;
    private javax.swing.JMenuItem business;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel city;
    private javax.swing.JLabel city1;
    private javax.swing.JLabel city2;
    private javax.swing.JLabel city3;
    private javax.swing.JMenuItem close;
    private javax.swing.JMenuItem departure;
    private javax.swing.JMenuItem economy;
    public javax.swing.JButton exit;
    private javax.swing.JMenuItem first;
    private javax.swing.JMenu flight;
    private javax.swing.JLabel gender;
    private javax.swing.JMenuItem hotel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JMenuItem open;
    private javax.swing.JMenu precords;
    private javax.swing.JMenuItem premium;
    private javax.swing.JMenuItem quiz;
    public javax.swing.JButton reset;
    private javax.swing.JLabel store;
    public javax.swing.JButton submit;
    public javax.swing.JTextPane xaddress;
    public javax.swing.JTextPane xage;
    public javax.swing.JComboBox xarrival;
    public javax.swing.JComboBox xclass;
    public javax.swing.JComboBox xdepart;
    public com.toedter.calendar.JDateChooser xdepartdate;
    public javax.swing.JTextPane xemail;
    public javax.swing.JTextPane xname;
    public javax.swing.JTextPane xphone;
    public com.toedter.calendar.JDateChooser xreturndate;
    public javax.swing.JTextPane xseat;
    // End of variables declaration//GEN-END:variables
}
